"""empty message

Revision ID: 38e971511d82
Revises: None
Create Date: 2014-07-04 13:56:23.548847

"""

# revision identifiers, used by Alembic.
revision = '38e971511d82'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
