"""empty message

Revision ID: 59d4a88bf7a
Revises: 1c0253a73eac
Create Date: 2014-07-04 15:05:59.940584

"""

# revision identifiers, used by Alembic.
revision = '59d4a88bf7a'
down_revision = '1c0253a73eac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    ### end Alembic commands ###
